### ISSUE TITLE
Confusion on what this is vs. existing ac-infinity HACS integration; they use same folders etc!

### ISSUE THREAD

**Issue by douginoz** [dalinicus/homeassistant-acinfinity#38]
This new integration popped up in my HACS screen and it appears to be a completely independent integration.  However, there's already an existing ac-infinity-hacs integration by hunterjm and which saves it's configuration files in custom_components/ac_infinity, which is where this dalinicus/homeassistant-acinfinity integration also saves it's files.
So installing this one would corrupt the existing integration.

What I'm finding confusing is that there's absolutely no mention of the existing hunterjm/ac-infinity-hacs integration in the readme here, and there's no mention of this new integration if I search for it in /community.home-assistant.io.

So it would really help if there was some clarification of this new HACS integration as well as what to do if the other one is already installed, since it uses the same folder.

**Comment by dalinicus** [comment]
This is a completely separate, unrelated integration to what you currently have installed.  hacs/default approved us for inclusion in the default HACS listing yesterday afternoon, which is why it is appearing as an option now.  Previously you would have had to add us as a custom repository before installing.

Looking at the huterjm's repo... we just happen to both store our source in the `ac_infinity` folder.  If you wish to use this integration, you'll need to uninstall the other conflicting one.

Hope that clears up your confusion.

**Comment by douginoz** [comment]
Ah thanks for the reply.  When you say it's completely separate, does that mean it does a completely different function(s)? Or does it do the same as the other?

**Comment by dalinicus** [comment]
I'm not familiar with hunterjm's implementation personally.. but a cursory glance it looks like it might be a basic Bluetooth implementation?  This implementation is for the WIFI UIS controllers, which might be incompatible with your devices.

**Comment by douginoz** [comment]
Ah yes, I'm using the bluetooth model which doesn't have a cloud dependency.  If your integration is only for the controller 69 then it won't work with controller 67.  However, the start of your readme states:

"This is a custom component for [Home Assistant](http://home-assistant.io/) that adds support for AC Infinity grow tent devices within the Smart UIS Controller ecosystem".  The controller 67 is listed on that Smart UIS ecosystem web page that you link to (https://acinfinity.com/smart-controllers/).

So you might want to clarify at the start of your readme that your integration is only for controller 69.

**Comment by dalinicus** [comment]
Looking at the product specs... its not technically a UIS device, nor is it marketed as one within their own documentation, but it appears that UIS devices can be added to it via a molex adapter.  You're also right that them listing it on that page is confusing.  I'll update the readme to clear up future confusion.

**Comment by dalinicus** [comment]
https://github.com/dalinicus/homeassistant-acinfinity/commit/50d632b78a638d58fb1ed176c2305d2c0954ef9a

Done.  Thanks for the input!
