### ISSUE TITLE
PATCH calls to AC Infinity API cause subsiquent requests to API to fail or timeout for a period of time.

### ISSUE THREAD

**Issue by almighty059** [dalinicus/homeassistant-acinfinity#39]
When changing modes I started having  the following error message appear at the bottom of the screen...

![Screenshot 2023-11-25 175308](https://github.com/dalinicus/homeassistant-acinfinity/assets/63380298/053676a4-4f8d-4c66-8eb0-03562c76ba74)

This is what the log says...

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:39:53 PM (6 occurrences)
Last logged: 5:53:00 PM

[281473424745280] {'msg': 'Something went wrong with your request.\nPlease try again later.', 'code': 100001}
[281472154391232] {'msg': 'Something went wrong with your request.\nPlease try again later.', 'code': 100001}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 106, in async_select_option
    await entity.async_select_option(option)
  File "/config/custom_components/ac_infinity/select.py", line 49, in async_select_option
    await self.set_setting_value(
  File "/config/custom_components/ac_infinity/__init__.py", line 148, in set_setting_value
    await coordinator.ac_infinity.set_device_port_setting(
  File "/config/custom_components/ac_infinity/ac_infinity.py", line 219, in set_device_port_setting
    await self.set_device_port_settings(device_id, port_id, [(setting, value)])
  File "/config/custom_components/ac_infinity/ac_infinity.py", line 228, in set_device_port_settings
    await self._client.set_device_port_settings(
  File "/config/custom_components/ac_infinity/client.py", line 105, in set_device_port_settings
    _ = await self.__post(API_URL_ADD_DEV_MODE, payload, headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ac_infinity/client.py", line 119, in __post
    raise ACInfinityClientRequestFailed(json)
custom_components.ac_infinity.client.ACInfinityClientRequestFailed: {'msg': 'Something went wrong with your request.\nPlease try again later.', 'code': 100001}

```

**Comment by almighty059** [comment]
I deleted the entire integration and then re-downloaded it and installed it but I'm still getting the same error message. I have the update set to 30 seconds and when I change modes there's a long pause and then the mode changes and then the error message appears or the error message appears and then the mode changes.

**Comment by almighty059** [comment]
The same error is happening when I try to change other things besides the mode such as ON SPEED and OFF SPEED. I haven't tested everything but so far it seems to be happening with everything I try to change.

**Comment by dalinicus** [comment]
looks like your requests to the API are timing out.  I've noticed during development that the occasional request to the API would time out after an update operation, so I threw in some retry logic.  As I can see from the logs, it attempts to make the call 3 times before giving up.  Not sure why its happening more frequently for you... but that's the dangers of using a non-public API I guess :(  It's essentially a black box, so how to "properly" call it has to be reverse engineered and any errors that occur are essentially invisible. 

I'll convert this into a bug to investigate why patch (update) calls to the API cause it to hang on subsequent calls. 

One thing you can try is remove and re-add your Controller 69 from the AC Infinity app.  See if that doesn't clear any bad data on their end that may be causing issues.

**Comment by almighty059** [comment]
I'll try that to see what happens. And I don't know if it matters but the App itself is lagging when changing modes and settings. I get an error that says to try again at a later time but then the error clears and the change goes through.

**Comment by almighty059** [comment]
@dalinicus deleting the device from the app and the integration and adding it back worked. I'm no longer getting the error. Thanks.

**Comment by zpriddy** [comment]
I am having the same issue - when it stops responding, if I control it from the AC Infinity app.. it will start to work again after a reload.. but it keeps happening…

I will try to delete it from the app and re-add it

**Comment by dalinicus** [comment]
Would you mind providing what device modes your using, and what settings your frequently changing?  It would help me debug; I can throw a traffic spy on my phone and see if the app is sending values that the integration is missing.  Some of them (like temperature in auto mode) requires multiple values be to changed for it to work properly, and I could have missed it.

**Comment by Vandewaetere** [comment]
@dalinicus I am mainly updating the 'mode' (on or off) and the 'on fan speed' from HA. See also #47

**Comment by bert-the-dog** [comment]
Nothing really new to add, just to say i'm also getting this. For me, it's the changing of the fan on power value that does it. It still seems to update in the log when i change the speed in the app. However, this last time I've not been changing any settings for the last week or so & its still started to do it.

Like zpriddy above, the app itself seems to play up when this is happening & removing & adding it seems to sort it. It seems like it could be AC app issue? there's plenty of posts about problems with it elsewhere.

Also thanks for making this integration, really makes it easier to manage everything

**Comment by almighty059** [comment]
@bert-the-dog it might be an AC app issue. It occasionally happens to me too. I can't really narrow it down to what exactly it is. AC should be coming out with a new version of the app sometime soon because the current version of the app doesn't handle all of the features of the new fan. And FYI if you have an old fan they'll swap it out for the new version which has some major improvements.

**Comment by maziggy** [comment]
I hame the same issue since two days now. Just deleted the controller from the app and I'm not able to add it again. The app finds the controller, connects via BT and set the WIFI details. This seems to be successfull because after that the controller is connected to the WIFI network. But then it stucks and don't add the controller to the inventory.

Any ideas please?

**Comment by maziggy** [comment]
Just asked customer support.

"It appears to be a server overload issue. We are trying to resolve that shortly."

**Comment by Kaeroe** [comment]
There seriously needs to be some kind of local control project started.. with the almost constant timeout failures and now 2 days of uncontrollable devices due to their "scheduled"server maintenance.. so scheduled that it began half a day before any notification 
My poor pet toad was getting completely drenched by their humidifier turning on from my automation but not able to turn off.. had to disconnect from the mains and use a manual fan to try and dry out his enclosure a bit.

**Comment by dalinicus** [comment]
> There seriously needs to be some kind of local control project started.. 

When I was first developing the initial integration, there was a forum thread of users looking into Bluetooth support for the 67 models.  They didn't look like they were making much progress, which is why I started this project.  I haven't followed up since to see if they were successful.

Based on our observations over the last 9 months, and the amount of experimental coding I've done, I think we can confidently conclude that the issues reported above are results of instability in the API rather than this integration.  As there is really nothing we can do on the integration side to resolve this, I'm going to close this Issue for now.  If I'm missing any valid takeaways above, please salvage them to a new Issue.
