### ISSUE TITLE
RFE: support updating the user/pass information

### ISSUE THREAD

**Issue by pcmoore** [dalinicus/homeassistant-acinfinity#43]
**Is your feature request related to a problem? Please describe.**
No, although it is mildly annoying to have to delete the integration device and re-add it to update the user/pass login information.

**Describe the solution you'd like**
It would be nice if the Web UI configuration option allowed the user to update the login credentials along with the polling interval.

Thanks!

**Comment by dalinicus** [comment]
Linked PR adds support for changing password via the options dialog.  Unfortunately, e-mail is intrinsically tried to the configuration and cannot be changed by design, so it can only be changed by re-adding the configuration.

Thanks for the idea!
