### ISSUE TITLE
Values to store as statistics 

### ISSUE THREAD

**Issue by akballow** [dalinicus/homeassistant-acinfinity#46]
All the values like temperature, humidity, and VPD do not store as statistics so I cannot see the values in default statistics 
 graph.

Am I doing something wrong? Or is this something that has not been done yet?

Thank you and sorry if this was user error.

**Comment by dalinicus** [comment]
Are you referring to the history graph on the sensor? 

![image](https://github.com/dalinicus/homeassistant-acinfinity/assets/8620219/8e4b11ad-3e6e-4dbf-9b04-e3b260a10edb)

This is part of home assistant core functionality for sensor entities, and not something that needs to be setup explicitly by this integration.  It also appears to be functioning as expected for me.

If this is not what you're referring to, could you please elaborate further on what graphs you are referring to.

**Comment by akballow** [comment]
> Are you referring to the history graph on the sensor?
> 
> ![image](https://private-user-images.githubusercontent.com/8620219/300216918-8e4b11ad-3e6e-4dbf-9b04-e3b260a10edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTExNDgsIm5iZiI6MTcwNjM5MDg0OCwicGF0aCI6Ii84NjIwMjE5LzMwMDIxNjkxOC04ZTRiMTFhZC0zZTZlLTRkYmYtOWIwNC1lM2IyNjBhMTBlZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMjEyNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ2YWEwNDgzZTZmMTY5NmFhN2FiNTExYjVhOTNmMGM5Yzc3NGZiMDE3YTk1MTg3YjQ2Nzc0NTM0OWQwYTJlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jr7XALUGdH0Xz79nbkircj2ORsVOxPN4jC42UkLi2mg)
> 
> This is part of home assistant core functionality for sensor entities, and not something that needs to be setup explicitly by this integration. It also appears to be functioning as expected for me.
> 
> If this is not what you're referring to, could you please elaborate further on what graphs you are referring to.

Hi thanks for the reply. No the history graph is fine but home assistant has a statistics graph which the same entities will not work for because the values are not written to a statistics value. This allows for averages, min, and max which is much more informative than the history graph.

**Comment by dalinicus** [comment]
Sorry, I spaced on getting more information on this.  

https://www.home-assistant.io/integrations/statistics/

Is this what you're referring to?  It looks like it just keeps track of an existing sensor or binary sensor (number, select, switch, and time do not appear to be supported) and doesn't appear to require anything special from the sensor itself other than it reporting its normal values.

Could you send one or more of the following items?
- a few screenshot of it not working
- documentation on which fields you believe are not being set
- if the above link is not what you're referring to, a link to the HomeAssistant documentation of the feature you're attempting to use

**Comment by Icevarta** [comment]
Hi, i think akballow is talking about the Long-term Statistics. They are needed for the Statistics graph card. At the Moment the entities of this component do not show up in the Entity select field.

<img width="1004" alt="Bildschirmfoto 2024-04-08 um 16 58 10" src="https://github.com/dalinicus/homeassistant-acinfinity/assets/5417954/7c07f539-5dad-4cc9-8d29-b9a98b3ec713">


The handy "Why is my entity not listed?" link leads to this page:
[Long-term Statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
Seems like the sensors need the `state_class ` property  set to `measurement `.

**Comment by dalinicus** [comment]
Perfect.   Thanks for the clarification.  I'll take a look.

**Comment by dalinicus** [comment]
Thiis is available in [version 1.4.3](https://github.com/dalinicus/homeassistant-acinfinity/releases/tag/1.4.3).  Thanks all :)
