### ISSUE TITLE
VPD defaults to incorrent Unit of Measurement (PSI and not kPa)

### ISSUE THREAD

**Issue by almighty059** [dalinicus/homeassistant-acinfinity#49]
The linked PR has nothing to do with this issue, as it was intended for a completely different integration by the same name that I do not maintain.  That being said, HomeAssistant core changed something with how `unit_of_measurement` and `native_unit_of_measurement` work...  I had a similar issue with another extension I maintain.  Would you mind creating a separate issue thread for this, and I'll check it out?

example from the codebase.  I assume I'll need to switch this to `unit_of_measurement` instead.
![image](https://github.com/dalinicus/homeassistant-acinfinity/assets/8620219/51922763-cda0-43a7-89de-e88b8a679cf9)

_Originally posted by @dalinicus in https://github.com/dalinicus/homeassistant-acinfinity/issues/37#issuecomment-1946842714_

Issue involving VPD defaulting to incorrect Unit of Measurement for VPD. It seems to default to PSI when it should be kPa.

**Comment by dalinicus** [comment]
Thanks for splitting this out 👍🏻.  Might have some time this weekend to knock this out.

**Comment by dalinicus** [comment]
This should be fixed in [1.4.1](https://github.com/dalinicus/homeassistant-acinfinity/releases/tag/1.4.1).  Thanks for the report!
