### ISSUE TITLE
Include leaf temperature offset from controller settings (r/w)

### ISSUE THREAD

**Issue by Fabelwesen** [dalinicus/homeassistant-acinfinity#57]
I plan to install a thermal imaging camera in my grow environment so that I have a live temperature reading of the leaf surfaces. From this, I can then calculate the offset to the air temperature, ensuring that the VPD value is always calculated correctly and the controller acts accordingly.

Would it be possible to read the current offset from the controller settings via API and include it in the integration, so that it can be adjusted automatically?

**Comment by dalinicus** [comment]
Thanks for the feedback.  This feature is now available in [1.5.0](https://github.com/dalinicus/homeassistant-acinfinity/releases/tag/1.5.0)
