### ISSUE TITLE
Alternative for Scraping API Key

### ISSUE THREAD

**Issue by dwot** [dalinicus/homeassistant-acinfinity#6]
Love the work, played around and used the techniques to implement my own quick and dirty app to read sensor data and state and write them to text files for display on my twitch stream.  I didn't love the process of getting the API key, trial install of fiddler just seemed a bit too bulky for the tiny need, so I wrote a quick and simple go app to spin up a proxy server and simply write out the API key and user-agent strings to the console once spotted.  Certainly nothing wrong w/ the Fiddler approach but figured you may be interested in a simpler alternative, if so, the code and release can be found at https://github.com/dwot/ACScraper

Thanks again for all the work here!

--dwot

**Comment by dalinicus** [comment]
So funny story.. I'm actually working on a username/password login flow as we speak :P should be pushed out in a few hours.
