### ISSUE TITLE
Pro Controller Features

### ISSUE THREAD

**Issue by maziggy** [dalinicus/homeassistant-acinfinity#61]
Are there any plans to integrate the Pro controller funtions like port transition/buffer settings?

<img width="289" alt="Screenshot 2024-08-03 at 08 44 56" src="https://github.com/user-attachments/assets/6be1b3f8-0a9a-456e-9d14-4180108dea7d">

**Comment by dalinicus** [comment]
I'll take a look. 👍🏻

**Comment by dalinicus** [comment]
Thanks for the feedback. This feature is now available in [1.6.0](https://github.com/dalinicus/homeassistant-acinfinity/releases/tag/1.6.0)

**Comment by maziggy** [comment]
Works like charm. Thanks!
