### ISSUE TITLE
Feature: Device Active/Inactive

### ISSUE THREAD

**Issue by almighty059** [dalinicus/homeassistant-acinfinity#67]
Is there anyway to add an entity to the device that shows if the device is powered on or off? This way either the integration itself or the user can set a condition to first check the state before even attempting to send a command? This would help to prevent accidental calls to the controller when it isn't even powered on. This is different than the entity that shows plugged in or unplugged because these (as well as other entities) will remain showing a false state when the entire controller loses power.

**Comment by dalinicus** [comment]
If I'm understanding correctly, I don't remember seeing anything that would indicate a "has AC power" but I can poke around in some captures to see if anything pops out.

The difficult part here is that we're not actually communicating with the controller directly, but rather the API in between HA and the Controller.  When the controller disconnects from WIFI, the API is still going to keep reporting the last values it received from the controller.  Unless there is a field in the data that would indicate that contact was lost with device... there's no way for us to tell if thats the case on the HA's side.

That being said, because calls are going out to the API and not the device directly, the device should pick up that configuration change the next time it connects to WIFI.

**Comment by almighty059** [comment]
Okay. I didn't realize that it was through the api and not the controller. For some reason I thought you had to setup the integration to go through the controller but i guess that wouldn't make much sense. And you're right, there's probably no data point that would show if it's powered or not powered. I also don't think it would change once powered on like you said because the error I get when something is off and I accidentally attempt to change it is "_Failed to perform the action select/select_option. {'msg': 'Check your WiFi settings and try again.', 'code': 500}_". So I don't think it remembers the change for when the controller is powered on. If you do poke around, look for what the api and app uses to grey out the controller on the app when it's not powered. There must be some type of data that is sent between them which the app or the api uses to grey out the controller when it's not receiving power from any device right?

**Comment by dalinicus** [comment]
>  "Failed to perform the action select/select_option. {'msg': 'Check your WiFi settings and try again.', 'code': 500}".

Okay that's good to know.  We could possibly use that in the absence of something better.  But yeah, hoping for field value instead.  Good point on the "greyed out".. hopefully there is an actual field then.

**Comment by almighty059** [comment]
And I apologize if I don't use the technical turns the right way. Lol.

And as a sidenote, is there anything that you could incorporate for deleting a controller? When I delete one in the app it stays in the integration which I assume is probably because the information itself is being retained in the api. Not a big deal for me because I just go into the core registry entity and device files and manually delete them but for someone with less HA knowledge it might be a problem. It's not a priority but just something to think about. I ran into the issue when I had to warranty a controller and then upgraded another. I had to go in and manually delete the old ones so I could use their names for the new controllers.

Thanks again for all of the work you put in on this.... 💯

**Comment by almighty059** [comment]
Here's what my current UI looks like courtesy of all your hard work...

![ezgif-7-25b30475e1](https://github.com/user-attachments/assets/0209670e-976c-41eb-8526-25268c172299)

**Comment by dalinicus** [comment]
> And I apologize if I don't use the technical turns the right way. Lol.
lol your good

> And as a sidenote, is there anything that you could incorporate for deleting a controller
entities for all integrations are added to home assistant on first load.  If you reboot home assistant, or reload the integration from the Integration screen, the old entities from the deleted controller will disappear once the integration reloads.

**Comment by dalinicus** [comment]
> Here's what my current UI looks like courtesy of all your hard work...

![magnum-45153619](https://github.com/user-attachments/assets/332e4d76-977b-42fa-972b-285c7a54f737)

**Comment by almighty059** [comment]
> entities for all integrations are added to home assistant on first load. If you reboot home assistant, or reload the integration from the Integration screen, the old entities from the deleted controller will disappear once the integration reloads.

For some reason this doesn't or at least hasn't recently worked for me. I think it previously did but I can't remember for sure. I tried multiple restarts, cleared the cache, and even waited a few days and tried again and even though the controller was no longer shown in the AC app the integration still displayed it as a working device with all of it's entities. Maybe it was just a weird glitch that I was experiencing. Idk. The deleted controller's device and entities didn't even show up in red like others normally do when disconnected. Instead they appeared as if they were all okay which didn't make sense. Not a big issue but I figured I'd bring it to your attention. Again, maybe it was just a weird glitch that I was experiencing. 

If you want me to test it let me know and I could delete one of the controllers that I'm currently not using and see what happens.

**Comment by almighty059** [comment]
@dalinicus did you get the coffee I sent.?

**Comment by dalinicus** [comment]
I did!  Thank you very much.   That's very kind of you <3

**Comment by dalinicus** [comment]
I did find a field that I overlooked.  After analyzing captured traffic, it seems to function like you'd expect.  Will be added in the next release.

I have one or two more features I want to get done before then, but should be within the next few days.

**Comment by dalinicus** [comment]
https://github.com/dalinicus/homeassistant-acinfinity/releases/tag/1.7.0
