### ISSUE TITLE
Feature: Humidifier - Auto Mode: Target Setting

### ISSUE THREAD

**Issue by Moe555** [dalinicus/homeassistant-acinfinity#70]
Hi,

The Auto Mode for the device type Humidifier has a target value setting, besides the usual high/low trigger approach.

![Foto 03 09 24, 19 57 56](https://github.com/user-attachments/assets/190246c1-0b5d-43e0-add6-8c54905977ba)

It would be cool if this could be reflected in the HA integration as well.

Thanks

**Comment by dalinicus** [comment]
https://github.com/dalinicus/homeassistant-acinfinity/releases/tag/1.7.0
