### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by jeffcybulski** [dalinicus/homeassistant-acinfinity#71]
@dalinicus where can I find the AC Infinity API? The references I find on the interwebs are broken.

**Comment by dalinicus** [comment]
There is no public API reference.  The API is only meant for their android/ios app, and this integration only works because they didn't implement better security validate where traffic is coming from.

 
I use a web proxy to intercept amd record traffic to get what I need.

**Comment by jeffcybulski** [comment]
Is there a way to capture events (e.g. fan turns on) and call other API? (e.g. turn off a Meross power switch or something)

**Comment by dalinicus** [comment]
Yes. The built-in Automation feature in HomeAssistant is what you're looking for.  You'd hook up your Meross power switch entities (or custom API call) in the "Then do" section.

![image](https://github.com/user-attachments/assets/3d1e796f-2e37-4672-9958-8d54ad5e57ec)

**Comment by dalinicus** [comment]
The "on state" of any ac infinity port is governed by "current power".. there isnt a binary on/off field in the api that ive found.  You'd have to cross check "current power" against "off speed" and "on speed"

**Comment by dalinicus** [comment]
[1.7.0]() adds a `State` field that indicates if a device is in the on or off state.  So what you're looking for is probably this
![image](https://github.com/user-attachments/assets/051f072a-1ef9-457b-b174-3204d9e2c3fe)

**Comment by jeffcybulski** [comment]
Thank you. I just wanted to say that your generous responses were enough to get me kick-started and hooked on Home Assistant. I am now motivated to take your reverse-engineering approach and apply it to iConnect for Mars Hydro!

**Comment by dalinicus** [comment]
Glad to hear it :) Let me know if you have any other questions.

**Comment by jeffcybulski** [comment]
Ryan, I am about to add the new AI advice and many devices are recognized. However, there is an error when trying to change any of the device settings.

LMK when you get your device and I’ll be happy to chip. Else, I could get debugging now...

**Comment by dalinicus** [comment]
Hey Jeff,  The AI controller is not currently supported.  I made the mistake of per-ordering multiple items, so I wont receive my AI controller until they're all ready.  I should receive it sometime this month, at which point I can begin work supporting the AI controller.

The open work item for this work is #88.

**Comment by EliteXCoder1** [comment]
@dalinicus So the http request are unencrypted between their server and the mobile app? I don't have a wifi enabled controller to test it, but i assume that;s the case since you are able to build this integration.

**Comment by dalinicus** [comment]
I haven't gone too deep into the AI controller changes to the API yet.  We got basic support going, but I'm working on a few QOL changes before I dig too deep into the new AI features.  The integration already adds too many controls and we need a way to manage that before we start adding more.

I use Burp suite and an android emulator to "man-in-the-middle" myself to inspect the API.  Unfortunately there is no public documentation.
